# Generated by Django 4.2.6 on 2023-10-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='url',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='named_url',
            field=models.CharField(max_length=100),
        ),
    ]
